version: '3'
volumes:
  vendor:
  storage_views:
  storage_cache:
services:
  app:
    container_name: restful-rss-app
    image: restful-rss/app
    build:
        context: ./
    volumes:
      - ./:/app
      - vendor:/app/vendor
      - storage_views:/app/storage/framework/views
      - storage_cache:/app/storage/framework/cache
    depends_on:
      - mongodb
    ports:
      - 8181:8181
  mongodb:
    container_name: restful-rss-mongodb
    image: mongo:3.7.9-jessie
    ports:
      - 27017:27017
