version: '3'
volumes:
  vendor:
  storage_views:
  storage_cache:
services:
  app:
    container_name: restful-rss-app
    image: restful-rss/app
    build:
        context: ./
    volumes:
      - ./:/app
      - vendor:/app/vendor
    depends_on:
      - mongodb
      - queue
      - worker
    ports:
      - 8181:8181
  worker:
    container_name: restful-rss-worker
    image: restful-rss/app
    command: php artisan queue:listen
    build:
      context: ./
    depends_on:
      - mongodb
      - queue
  mongodb:
    container_name: restful-rss-mongodb
    image: mongo:3.7.9-jessie
    ports:
      - 27017:27017
  queue:
    container_name: restful-rss-queue
    image: schickling/beanstalkd
    ports:
      - 11300:11300
